import type { BlogPage, PaperLink } from './types';

// 【修正】文字列を確実に「**/*.ts」に書き換えます。これでサブフォルダの奥までスキャンします
const modules = import.meta.glob('./pages/**/*.ts', { eager: true });

export const blogNetwork: Record<string, BlogPage> = {};

function getDeterministicValue(seedString: string, min: number, max: number): number {
  let hash = 0;
  for (let i = 0; i < seedString.length; i++) {
    hash = seedString.charCodeAt(i) + ((hash << 5) - hash);
  }
  const normalized = Math.abs(hash % 1000) / 1000;
  return min + normalized * (max - min);
}

for (const path in modules) {
  const mod = modules[path] as any;
  const pageData = mod.default as BlogPage;

  // 最後のファイル名（"t"）を自動抽出
  const autoGeneratedId = path.split('/').pop()?.replace('.ts', '') || '';

  if (pageData) {
    const fillMissingParams = (links: PaperLink[] | undefined, isLeft: boolean) => {
      if (!links) return [];
      return links.map((link, index) => {
        const seed = `${autoGeneratedId}-${link.id}-${index}`;

        return {
          id: link.id,
          x: link.x ?? Math.floor(getDeterministicValue(seed + '-x', isLeft ? 15 : 55, isLeft ? 45 : 85)),
          y: link.y ?? Math.floor(getDeterministicValue(seed + '-y', 15, 85)),
          r: link.r ?? Math.floor(getDeterministicValue(seed + '-r', -45, 45)),
          speed: link.speed ?? parseFloat(getDeterministicValue(seed + '-speed', 3.5, 6.5).toFixed(1)),
          rotSpeed: link.rotSpeed ?? parseFloat(getDeterministicValue(seed + '-rotSpeed', 5.0, 14.0).toFixed(1)),
          dir: link.dir ?? (getDeterministicValue(seed + '-dir', 0, 1) > 0.5 ? 1 : -1)
        };
      });
    };

    blogNetwork[autoGeneratedId] = {
      ...pageData,
      id: autoGeneratedId,
      leftLinks: fillMissingParams(pageData.leftLinks, true),
      rightLinks: fillMissingParams(pageData.rightLinks, false)
    };
  }
}
